services:
  mongo:
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - backend
    ports:
      - "8081:8081"


