version: '3'

networks:
    mongo-network:
      external: true
      name: 'mongo-net'
    redis-network:
      external: true
      name: 'redis-net'
    api-network:
      external: true
      name: 'api-net'

services:

  movies-api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017
      REDIS_URI: redis://redis
      ENABLE_WRITING_HANDLERS: 'false'
    ports:
      - "9000:9000"
    networks:
      - api-network
      - redis-network 
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network
      - api-network
    volumes:    
      - ./seed:/data/db 


  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    networks:
      - mongo-network
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - redis-network
    



